// src/app/about/page.jsx (or wherever your AboutUs component is located)
"use client";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { FaRegCheckCircle } from "react-icons/fa";
import axios from "axios";
import { useEffect, useState } from "react";
import AboutSection from "@/components/landing/aboutSection/aboutSection";
import WhyChooseUs from "@/components/landing/whytochoose";
import SubscribCard from "@/components/landing/partnersSection";

export function generatemetadata() {
  return {
    title: "About Us",
    description: "Generated by create REDVision Technologies.",
  };
}

export default function AboutUs() {
  const [siteSettings, setSiteSettings] = useState(null);

  useEffect(() => {
    const getData = async () => {
      const response = await axios.get("/api/admin/site-settings");
      console.log(response.statusText);
      if (response.statusText === "OK") {
        setSiteSettings(response.data[0]);
      }
    };
    getData();
  }, []);

  return (
    <div className="">
      {/* Hero Section */}
      <div className="flex bg-center bg-no-repeat bg-cover bg-[url('/images/pay-premium/pay-premium.webp')] overflow-hidden text-start justify-start items-center h-64">
        <div className="max-w-screen-xl mx-auto">
          <h1 className="text-gray-900 text-3xl md:text-5xl font-bold">
            Welcome to {siteSettings?.websiteName}
          </h1>
        </div>
      </div>

<AboutSection sitedata={siteSettings}/>

      {/* Introduction Section */}
      <motion.section
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1, delay: 0.2 }}
        className="main_section md:px-0 px-3"
      >
        {/* <h2 className="text-4xl text-[var(--rv-primary)] md:text-5xl font-bold mb-6 text-center">
          About Us
        </h2>
        <p className="text-gray-800 max-w-5xl mx-auto text-center mb-5">
          {siteSettings?.websiteName} is a Wealth Management/Financial Planning
          Firm. This Firm running by professionals and Experience Management.
          Our Expertise is in "Need Base Financial Planning" which helps our
          customers to achieve their Financial Goals with proper Risk
          Management.
        </p> */}

        {/* Top Features Section */}
        <h3 className="text-3xl text-center font-semibold text-[var(--rv-primary)] mb-6">
          Our Top Features
        </h3>
        <div className="grid md:grid-cols-3 sm:grid-cols-2 grid-cols-1 gap-6 max-w-6xl mx-auto px-4">
          {[
            "250+ Crore AUM",
            "Serving 1500+ Clients",
            "20+ Qualified Team Members",
            "Cutting Edge Technology",
            "30+ Years Combined Experience",
            "35+ Research Tools",
          ].map((feature, index) => (
            <div
              key={index}
              className="bg-white rounded-xl shadow-md p-6 text-center hover:shadow-lg transition duration-300"
            >
              <p className="text-lg font-medium text-gray-800">{feature}</p>
            </div>
          ))}
        </div>
      </motion.section>

      

      <div className="bg-[var(--rv-secondary)]">
        <div className="max-w-screen-xl mx-auto main_section md:px-0 px-3">
          {/* Transforming Ambitions Section */}
          <motion.section
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="grid grid-cols-1 md:grid-cols-2 gap-12 mb-6 items-center"
          >
            <div className="relative">
              <Image
                src="/images/about-us.webp"
                alt="About Us"
                width={550}
                height={550}
                className="rounded-xl grayscale shadow-lg"
              />
            </div>
            <div>
              <h2 className="text-3xl text-[var(--rv-primary)] md:text-4xl font-bold mb-6">
                How We Define "AntInvest"
              </h2>
              <p className="text-gray-100 mb-6">
                The name 'AntInvest' is derived from the word "ant", symbolizing
                diligence, teamwork, and strategic planning—traits essential to
                building and sustaining wealth. "Invest" reflects the core of
                our mission: thoughtful, purposeful financial growth. Together,
                "AntInvest" conveys a disciplined and collaborative approach to
                wealth management, where success is achieved not just through
                returns but through values-driven, sustainable practices. The
                name implies a commitment to growing wealth with responsibility,
                precision, and integrity.
              </p>
            </div>
          </motion.section>
        </div>
      </div>

      <WhyChooseUs sitedata={siteSettings}/>

      <div className="max-w-screen-xl mx-auto main_section md:px-0 px-3">
        {/* Mission, Vision, Value Section */}
        <motion.section
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 0.6 }}
          className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16"
        >
          <div className="group bg-[var(--rv-primary)] p-6 rounded-xl shadow-lg hover:scale-105 transition-transform">
            {/* <Image
              src="/svg/mission.svg"
              alt="Mission"
              width={60}
              height={60}
            /> */}
            <h3 className="text-2xl font-bold text-white my-3">Our Mission</h3>
            <p className="text-gray-100">
              We aspire to be known as "Wealth Creators & Financial Planners,
              driven by commitment and Core Values.
            </p>
          </div>
          <div className="group bg-[var(--rv-primary)] p-6 rounded-xl shadow-lg hover:scale-105 transition-transform">
            {/* <Image src="/svg/vision.svg" alt="Vision" width={60} height={60} /> */}
            <h3 className="text-2xl font-bold text-white my-3">Our Vision</h3>
            <p className="text-gray-100">
              To Educate and Empower the investors to make better investment
              decisions through, Quality Advice, Innovative Products, Superior
              Services.
            </p>
          </div>
        </motion.section>

        {/* Core Values */}
        <motion.section
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 1, delay: 0.6 }}
          className="mb-16 "
        >
          <h3 className="text-3xl  font-semibold text-[var(--rv-primary)] text-center mb-6">
            Core Values
          </h3>
          <p className="text-center max-w-3xl mx-auto text-gray-700 mb-4">
            We firmly believe that our Core Values have served as the
            Cornerstone for the Expansion and Success of our Company.
          </p>
          <ul className="grid sm:grid-cols-2 md:grid-cols-3 gap-4 text-center max-w-4xl mx-auto">
            {[
              "Financial Education",
              "Commitment",
              "Speed",
              "Transparency",
              "Client Centric Approach",
            ].map((value, i) => (
              <li
                key={i}
                className="bg-gray-100 p-4 rounded-lg shadow text-[var(--rv-primary)] font-semibold"
              >
                {value}
              </li>
            ))}
          </ul>
        </motion.section>
      </div>

      

      <div className="bg-[var(--rv-secondary)]">
        <div className="max-w-screen-xl mx-auto main_section md:px-0 px-3">
          <motion.section
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, delay: 0.8 }}
            className="mb-20"
          >
            <h2 className="text-2xl md:text-4xl lg:text-5xl font-bold text-white mb-12 text-center">
              Meet the Minds Powering the Future of Wealth Management
            </h2>
            <div className="mb-12">
              <div className="group bg-[var(--rv-primary)] p-8 rounded-xl shadow-lg transition-transform transform hover:scale-105 hover:shadow-2xl mb-10">
                <div className="grid md:grid-cols-6 justify-center gap-5">
                  <div className="md:col-span-2">
                    <Image
                      src="/anuj.jpg" // Make sure this image is available in your public folder
                      alt="Mr. ANUJ"
                      width={380}
                      height={380}
                      className="rounded grayscale group-hover:grayscale-0 transition-all mr-4"
                    />
                  </div>
                  <div className="md:col-span-4">
                    <div>
                      <h3 className="text-2xl font-bold text-white pt-0 mt-0 mb-4">
                        Mr. ANUJ
                      </h3>
                    </div>
                    <p className="text-gray-100 mb-4">
                      Mr. Anuj is a Strategic Investment Advisor, Personal
                      Finance Mentor, and Co-Founder of{" "}
                      {siteSettings?.websiteName}.
                    </p>
                    <p className="text-gray-100 mb-4">
                      With over 18 years of experience in wealth management, Mr.
                      Anuj has played a pivotal role in guiding individuals and
                      businesses towards achieving their financial aspirations
                      through personalized strategies and disciplined execution.
                    </p>
                    <p className="text-gray-100 mb-4">
                      He co-founded {siteSettings?.websiteName} to bridge the
                      gap between financial knowledge and action. The platform
                      offers a comprehensive suite of solutions including Mutual
                      Funds, Life & General Insurance, Bonds, PMS, AIF, and
                      more—catering to 1200+ satisfied clients nationwide.
                    </p>
                    <p className="text-gray-100 mb-4">
                      Mr. Anuj is deeply committed to investor education.
                      Through workshops, webinars, and one-on-one coaching, he
                      empowers clients with practical insights on wealth
                      accumulation, risk management, and financial independence.
                    </p>
                  </div>
                </div>

                <div className="">
                  <h4 className="text-xl font-semibold text-white mb-2">
                    Quick Bio
                  </h4>
                  <ul className="list-disc pl-5 space-y-2 text-gray-100">
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      Certified Financial Planner (FPSB India)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      MBA in Finance (Mumbai University)
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      NSE Certified Market Professional - Level 1 & 2
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      Founder - Financial Literacy Initiative “SmartInvest
                      Talks”
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      Author of the upcoming book “Money Mastery for
                      Millennials”
                    </li>
                    <li className="flex items-start gap-2">
                      <FaRegCheckCircle className="text-white text-2xl" />
                      Featured speaker at finance conclaves and investor
                      awareness programs
                    </li>
                  </ul>
                </div>
              </div>

              <div className="group bg-[var(--rv-primary)] p-8 rounded-xl shadow-lg transition-transform transform hover:scale-105 hover:shadow-2xl">
                <div className="grid md:grid-cols-6 justify-center md:gap-5">
                  <div className="md:col-span-4 mb-4">
                    <div>
                      <h3 className="text-2xl font-bold text-white pt-0 mt-0 mb-4">
                        Ms. SHIKHA PANDEY (CFP)
                      </h3>
                    </div>
                    <p className="text-gray-100 mb-4">
                      Shikha is the Director & Head of Financial Planning at{" "}
                      {siteSettings?.websiteName}. She is driven by a passion to
                      educate and empower individuals to take charge of their
                      financial future through strategic wealth planning and
                      disciplined investing.
                    </p>
                    <p className="text-gray-100 mb-4">
                      With a strong background in financial research and
                      advisory, she specializes in crafting personalized
                      financial plans tailored to unique goals and risk
                      profiles. Shikha actively conducts financial literacy
                      seminars and is recognized for her client-first approach
                      and analytical depth in Mutual Fund and Insurance product
                      recommendations.
                    </p>

                    {/* Quick Bio */}
                    <div className="mt-6">
                      <h4 className="text-xl font-semibold text-white mb-2">
                        Quick Bio
                      </h4>
                      <ul className="list-disc pl-5 space-y-2 text-gray-100">
                        <li className="flex items-start gap-2">
                          <FaRegCheckCircle className="text-white text-2xl" />
                          Certified Financial Planner (CFP - FPSB India)
                        </li>
                        <li className="flex items-start gap-2">
                          <FaRegCheckCircle className="text-white text-2xl" />
                          AMFI Certified - NISM
                        </li>
                        <li className="flex items-start gap-2">
                          <FaRegCheckCircle className="text-white text-2xl" />
                          IRDA Certified for Life & Health Insurance
                        </li>
                        <li className="flex items-start gap-2">
                          <FaRegCheckCircle className="text-white text-2xl" />
                          MBA in Finance (Delhi University)
                        </li>
                        <li className="flex items-start gap-2">
                          <FaRegCheckCircle className="text-white text-2xl" />
                          Author of Financial Wellness blog “PlanWell”
                        </li>
                        <li className="flex items-start gap-2">
                          <FaRegCheckCircle className="text-white text-2xl" />
                          Speaker at multiple women-focused financial
                          empowerment forums
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div className="md:col-span-2 col-span-4">
                    <Image
                      src="/shikhapandey.jpg" // Ensure the image exists in your public folder
                      alt="Shikha Pandey"
                      width={300}
                      height={80}
                      className="rounded grayscale group-hover:grayscale-0 transition-all mr-4"
                    />
                  </div>
                </div>
              </div>
            </div>
          </motion.section>
        </div>
      </div>

<SubscribCard sitedata={siteSettings}/>
      <div className="max-w-screen-xl mx-auto main_section">
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 1 }}
          className="text-center"
        >
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Join Us on a Journey to Infinite Growth!
          </h2>
          <p className=" text-gray-700 max-w-3xl mx-auto mb-8">
            At {siteSettings?.websiteName} , we don’t just manage wealth—we
            shape financial futures. Join us in transforming financial growth
            for business owners across India. Together, we’ll redefine what’s
            possible.
          </p>
          <Link href="/contact-us">
            <button className="primarybutton">Get Started</button>
          </Link>
        </motion.section>
      </div>
    </div>
  );
}
